# version: '3.8'

services:
  api:
    build: .
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - ENVIRONMENT=test
      - DATABASE_URL=postgresql://test_user:test_password@db:5432/test_db
      - REDIS_URL=redis://redis:6379/1
    command: pytest -v --cov=api --cov-report=term-missing
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
